services:
  - type: web
    name: user-activity-notification-system
    env: java
    buildCommand: ./mvnw clean install
    startCommand: ./mvnw spring-boot:run
    plan: free
    region: oregon
    branch: main
    runtime: java
